# Generated by Django 5.0.2 on 2024-04-18 07:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0004_alter_producttable_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="productTable",
        ),
    ]
