# Generated by Django 5.0.2 on 2024-04-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0008_productcategory_producttable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttable",
            name="productId",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
