# Generated by Django 5.0.2 on 2024-04-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0009_alter_producttable_productid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttable",
            name="description",
            field=models.TextField(max_length=1000),
        ),
    ]
