# Generated by Django 5.0.2 on 2024-04-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0010_alter_producttable_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttable",
            name="product_img",
            field=models.ImageField(
                blank=True, null=True, unique=True, upload_to="product_image/"
            ),
        ),
    ]
